# Generated by Django 6.0.4 on 2026-05-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('instituicao', 'nome')},
        ),
    ]
