# Generated by Django 6.0.4 on 2026-04-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_movimentacoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movimentacoes',
            new_name='Movimentacao',
        ),
    ]
