# Generated by Django 6.0.4 on 2026-04-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_rename_movimentacoes_movimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantidade',
        ),
    ]
