# Generated by Django 6.0.4 on 2026-04-21 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_remove_material_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='materiais.material'),
        ),
    ]
