# Generated by Django 6.0.4 on 2026-04-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0005_alter_movimentacao_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
