# Generated by Django 6.0.4 on 2026-04-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_movimentacao_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
